export const REQUEST_USER = 'REQUEST_USER'
export const RECEIVE_USER = 'RECIEVE_USER'
export const INVALIDATE_USER = 'INVALIDATE_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

//UI
export const TOGGLE_MODAL_ADD = 'TOGGLE_MODAL_ADD'
