//User
export const REQUEST_USER = 'REQUEST_USER'
export const RECEIVE_USER = 'RECIEVE_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

//Data
export const TOGGLE_TOPIC = 'TOGGLE_TOPIC'
export const ADD_TOPIC = 'ADD_TOPIC'
export const ADD_SUBTOPIC = 'ADD_SUBTOPIC'

//UI
export const TOGGLE_MODAL_ADD = 'TOGGLE_MODAL_ADD'
export const TOGGLE_MODAL_CREATE = 'TOGGLE_MODAL_CREATE'
export const TOGGLE_MODAL_CREATE_SUBTOPIC = 'TOGGLE_MODAL_CREATE_SUBTOPIC'
